[package]
name = "config-types-proc-macro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.3"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "1.0.76", features = ["full", "extra-traits"] }
