[workspace]
resolver = "2"
members = [
    ".",
]

[package]
name = "xfce-config"
version = "0.1.0"
authors = ["Daniel Beckwith <djbsnx@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.43"
indexmap = { version = "1.7.0", features = ["serde"] }
quick-xml = "0.22.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
